Update vite dependency to v4.
Updating vite to v4 fixes the error below (sveltekit requires v4)

``
failed to load config from vite.config.js
error when starting dev server:
node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:6
import { isCSSRequest, loadEnv } from 'vite';
SyntaxError: The requested module 'vite' does not provide an export named 'isCSSRequest'
``

Once I made this change all of the scripts run without errors.